import utils
import automateichon
import automataEsq
import nfaToDfa
import toAutomata
def matching(automata, texto):
    opts = list(texto)
    est = [0]
    est = utils.cerraduraEpsilon(automata, est)
    q = 0
    while True:
        temporales = []
        for es in est:
            for trans in automata.states[es].transitions:
                if trans.simbolo == opts[q] and trans.destino not in temporales:
                    temporales.append(trans.destino)
        q += 1
        temporales = utils.cerraduraEpsilon(automata, temporales)
        if not temporales and opts == utils.EPSILON:
            break
        est = temporales.copy()
        if q > len(opts)-1:
            break
    for x in est:
        if automata.states[x].accept:
            return True
    return False
def longest_string(file, automata, current = 0):
    temp = ''
    valid = []
    while current < len(file):
        temp += file[current]
        if matching(automata, temp):
            valid.append(temp)
        current += 1
    if valid:
        return max(valid, key = len)
    return False
def main():
    automatas = []
    automata0 = automataEsq.Machine("el grande")
    tempNode = automataEsq.State(0)
    trans = automataEsq.Transition('ε' , 0)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 1)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 2)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 3)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 4)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 5)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 6)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 7)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 8)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 9)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 10)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 11)
    tempNode.transitions.append(trans)
    automata0.states.append(tempNode)
    tempNode = automataEsq.State(1)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 1)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 13)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 20)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 21)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 22)
    tempNode.transitions.append(trans)
    automata0.states.append(tempNode)
    tempNode = automataEsq.State(2)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 2)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 23)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 20)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 21)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 22)
    tempNode.transitions.append(trans)
    automata0.states.append(tempNode)
    tempNode = automataEsq.State(3)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 3)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 23)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 20)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 21)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 22)
    tempNode.transitions.append(trans)
    automata0.states.append(tempNode)
    tempNode = automataEsq.State(4)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 4)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 23)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 20)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 21)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 22)
    tempNode.transitions.append(trans)
    automata0.states.append(tempNode)
    tempNode = automataEsq.State(5)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 5)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 23)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 20)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 21)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 22)
    tempNode.transitions.append(trans)
    automata0.states.append(tempNode)
    tempNode = automataEsq.State(6)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 6)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 23)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 20)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 21)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 22)
    tempNode.transitions.append(trans)
    automata0.states.append(tempNode)
    tempNode = automataEsq.State(7)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 7)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 23)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 20)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 21)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 22)
    tempNode.transitions.append(trans)
    automata0.states.append(tempNode)
    tempNode = automataEsq.State(8)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 8)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 23)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 20)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 21)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 22)
    tempNode.transitions.append(trans)
    automata0.states.append(tempNode)
    tempNode = automataEsq.State(9)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 9)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 23)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 20)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 21)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 22)
    tempNode.transitions.append(trans)
    automata0.states.append(tempNode)
    tempNode = automataEsq.State(10)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 10)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 24)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 25)
    tempNode.transitions.append(trans)
    automata0.states.append(tempNode)
    tempNode = automataEsq.State(11)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 11)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 24)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 25)
    tempNode.transitions.append(trans)
    automata0.states.append(tempNode)
    tempNode = automataEsq.State(12)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 23)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 20)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 21)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 22)
    tempNode.transitions.append(trans)
    automata0.states.append(tempNode)
    tempNode = automataEsq.State(13)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 13)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 23)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 20)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 21)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 22)
    tempNode.transitions.append(trans)
    automata0.states.append(tempNode)
    tempNode = automataEsq.State(14)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 23)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 20)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 21)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 22)
    tempNode.transitions.append(trans)
    automata0.states.append(tempNode)
    tempNode = automataEsq.State(15)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 23)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 20)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 21)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 22)
    tempNode.transitions.append(trans)
    automata0.states.append(tempNode)
    tempNode = automataEsq.State(16)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 23)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 20)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 21)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 22)
    tempNode.transitions.append(trans)
    automata0.states.append(tempNode)
    tempNode = automataEsq.State(17)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 23)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 20)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 21)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 22)
    tempNode.transitions.append(trans)
    automata0.states.append(tempNode)
    tempNode = automataEsq.State(18)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 23)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 20)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 21)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 22)
    tempNode.transitions.append(trans)
    automata0.states.append(tempNode)
    tempNode = automataEsq.State(19)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 23)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 20)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 21)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 22)
    tempNode.transitions.append(trans)
    automata0.states.append(tempNode)
    tempNode = automataEsq.State(20)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 20)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 23)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 20)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 21)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 22)
    tempNode.transitions.append(trans)
    automata0.states.append(tempNode)
    tempNode = automataEsq.State(21)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 21)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 23)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 20)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 21)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 22)
    tempNode.transitions.append(trans)
    automata0.states.append(tempNode)
    tempNode = automataEsq.State(22)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 22)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 23)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 20)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 21)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 22)
    tempNode.transitions.append(trans)
    automata0.states.append(tempNode)
    tempNode = automataEsq.State(23)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 23)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 23)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 20)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 21)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 22)
    tempNode.transitions.append(trans)
    automata0.states.append(tempNode)
    tempNode = automataEsq.State(24)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 24)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 24)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 25)
    tempNode.transitions.append(trans)
    automata0.states.append(tempNode)
    tempNode = automataEsq.State(25)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 25)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 24)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 25)
    tempNode.transitions.append(trans)
    automata0.states.append(tempNode)
    automatas.append(automata0)

    automata1 = automataEsq.Machine("if")
    tempNode = automataEsq.State(0)
    trans = automataEsq.Transition('ε' , 0)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 1)
    tempNode.transitions.append(trans)
    automata1.states.append(tempNode)
    tempNode = automataEsq.State(1)
    trans = automataEsq.Transition('ε' , 1)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 2)
    tempNode.transitions.append(trans)
    automata1.states.append(tempNode)
    tempNode = automataEsq.State(2)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 2)
    tempNode.transitions.append(trans)
    automata1.states.append(tempNode)
    automatas.append(automata1)

    automata2 = automataEsq.Machine("id")
    tempNode = automataEsq.State(0)
    trans = automataEsq.Transition('ε' , 0)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 1)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 2)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 3)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 4)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 5)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 6)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 7)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 8)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 9)
    tempNode.transitions.append(trans)
    automata2.states.append(tempNode)
    tempNode = automataEsq.State(1)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 1)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 10)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 11)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 13)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 20)
    tempNode.transitions.append(trans)
    automata2.states.append(tempNode)
    tempNode = automataEsq.State(2)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 2)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 10)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 11)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 13)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 20)
    tempNode.transitions.append(trans)
    automata2.states.append(tempNode)
    tempNode = automataEsq.State(3)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 3)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 10)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 11)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 13)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 20)
    tempNode.transitions.append(trans)
    automata2.states.append(tempNode)
    tempNode = automataEsq.State(4)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 4)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 10)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 11)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 13)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 20)
    tempNode.transitions.append(trans)
    automata2.states.append(tempNode)
    tempNode = automataEsq.State(5)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 5)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 10)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 11)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 13)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 20)
    tempNode.transitions.append(trans)
    automata2.states.append(tempNode)
    tempNode = automataEsq.State(6)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 6)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 10)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 11)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 13)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 20)
    tempNode.transitions.append(trans)
    automata2.states.append(tempNode)
    tempNode = automataEsq.State(7)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 7)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 10)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 11)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 13)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 20)
    tempNode.transitions.append(trans)
    automata2.states.append(tempNode)
    tempNode = automataEsq.State(8)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 8)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 10)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 11)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 13)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 20)
    tempNode.transitions.append(trans)
    automata2.states.append(tempNode)
    tempNode = automataEsq.State(9)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 9)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 10)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 11)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 13)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 20)
    tempNode.transitions.append(trans)
    automata2.states.append(tempNode)
    tempNode = automataEsq.State(10)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 10)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 10)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 11)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 13)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 20)
    tempNode.transitions.append(trans)
    automata2.states.append(tempNode)
    tempNode = automataEsq.State(11)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 11)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 10)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 11)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 13)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 20)
    tempNode.transitions.append(trans)
    automata2.states.append(tempNode)
    tempNode = automataEsq.State(12)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 10)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 11)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 13)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 20)
    tempNode.transitions.append(trans)
    automata2.states.append(tempNode)
    tempNode = automataEsq.State(13)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 13)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 10)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 11)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 13)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 20)
    tempNode.transitions.append(trans)
    automata2.states.append(tempNode)
    tempNode = automataEsq.State(14)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 10)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 11)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 13)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 20)
    tempNode.transitions.append(trans)
    automata2.states.append(tempNode)
    tempNode = automataEsq.State(15)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 10)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 11)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 13)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 20)
    tempNode.transitions.append(trans)
    automata2.states.append(tempNode)
    tempNode = automataEsq.State(16)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 10)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 11)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 13)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 20)
    tempNode.transitions.append(trans)
    automata2.states.append(tempNode)
    tempNode = automataEsq.State(17)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 10)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 11)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 13)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 20)
    tempNode.transitions.append(trans)
    automata2.states.append(tempNode)
    tempNode = automataEsq.State(18)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 10)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 11)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 13)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 20)
    tempNode.transitions.append(trans)
    automata2.states.append(tempNode)
    tempNode = automataEsq.State(19)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 10)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 11)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 13)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 20)
    tempNode.transitions.append(trans)
    automata2.states.append(tempNode)
    tempNode = automataEsq.State(20)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 20)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('a' , 10)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('b' , 11)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('c' , 12)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('d' , 13)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('e' , 14)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('f' , 15)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('g' , 16)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('h' , 17)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('i' , 18)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 19)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 20)
    tempNode.transitions.append(trans)
    automata2.states.append(tempNode)
    automatas.append(automata2)

    automata3 = automataEsq.Machine("numero")
    tempNode = automataEsq.State(0)
    trans = automataEsq.Transition('ε' , 0)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 1)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 2)
    tempNode.transitions.append(trans)
    automata3.states.append(tempNode)
    tempNode = automataEsq.State(1)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 1)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 3)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 4)
    tempNode.transitions.append(trans)
    automata3.states.append(tempNode)
    tempNode = automataEsq.State(2)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 2)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 3)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 4)
    tempNode.transitions.append(trans)
    automata3.states.append(tempNode)
    tempNode = automataEsq.State(3)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 3)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 3)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 4)
    tempNode.transitions.append(trans)
    automata3.states.append(tempNode)
    tempNode = automataEsq.State(4)
    tempNode.accept = True
    trans = automataEsq.Transition('ε' , 4)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('0' , 3)
    tempNode.transitions.append(trans)
    trans = automataEsq.Transition('1' , 4)
    tempNode.transitions.append(trans)
    automata3.states.append(tempNode)
    automatas.append(automata3)

    print('nombre de archivo:')
    test = input()
    filerino = open('/Users/cristinabautista/Desktop/Diseño Lenguajes/Proyecto2_DdL/Proyecto2/tests/' + test)
    words = filerino.read()
    filerino.close()
    i = 0
    last = 0
    while i < len(words):
        valid = longest_string(words, automata0, i)
        if valid:
            if last != 0 and (i - last > 0):
                while last < i:
                    last += 1
            last += len(valid)
            aut = 1
            while aut<len(automatas):
                if (matching(automatas[aut], valid)):
                    print(valid, 'is', automatas[aut].id)
                    break
                aut += 1
            i += len(valid)
        else:
            i+=1
if __name__ == "__main__":
   main()